version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app   #Monta i file locali nel container
      - /app/node_modules
    depends_on:
      - db

    env_file: .env

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app  #Monta i file locali nel container

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db-docker:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql